packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@scarf/scarf': false
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: false
  esbuild: true
  mongodb-memory-server: true
  msgpackr-extract: false
  protobufjs: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
overrides:
  prosemirror-model: ^1.22.3
  prosemirror-view: ^1.34.2
  '@types/react': 18.3.7
  '@types/react-dom': 18.3.0
  form-data: 4.0.5
  '@aws-sdk/core>fast-xml-parser': 4.5.4
  '@grpc/proto-loader>protobufjs': 7.5.7
  axios: 1.16.0
  fast-uri: 3.1.2
  '@xmldom/xmldom': 0.8.13
  kysely: 0.28.17
  lodash: 4.18.1
  lodash-es: 4.18.1
  express>path-to-regexp: 0.1.13
  handlebars: 4.7.9
