/**
 * This file provides application wide strings.
 */

export const ERR_ALL_FIELDS_REQUIRED = 'All fields are required.'
export const ERR_PASSWORDS_DONT_MATCH = 'Passwords do not match.'
export const SIGNUP_SUCCESS = 'Sign up successful. Please sign in.'
export const ERR_COURSE_TITLE_REQUIRED = 'A title is required.'
export const ERR_COURSE_COST_REQUIRED = 'Cost is required.'

// Replies from the backend
export const RESP_API_USER_CREATED = 'User created'

// Placeholder texts
export const CREATOR_AREA_LINK_TEXT = 'Create'
export const CREATOR_AREA_PAGE_TITLE = 'Dashboard'
export const GENERIC_TITLE = 'Content Platform'
export const GENERIC_SUBTITLE = 'Learn new topics'
export const GENERIC_LOGO_PATH = ''
export const GENERIC_SIGNIN_TEXT = 'Sign in'
export const GENERIC_SIGNUP_TEXT = 'Sign up'
export const GENERIC_SIGNOUT_TEXT = 'Sign out'
export const GENERIC_CURRENCY_UNIT = ''
export const GENERIC_COPYRIGHT_TEXT = `© ${(new Date()).getFullYear()}`
export const GENERIC_ABOUT_TEXT = ''

// UI texts
export const BTN_LOAD_MORE = 'Load More'
export const COURSE_CREATOR_BUTTON_TEXT = 'Save'
export const MEDIA_UPLOAD_BUTTON_TEXT = 'Upload'
export const ERR_MEDIA_UPLOAD_TITLE_TEXT = 'A title and a file are required'
export const MEDIA_ADD_NEW_BUTTON_TEXT = 'Add new'
export const BUTTON_CANCEL_TEXT = 'Cancel'
export const MEDIA_SEARCH_INPUT_PLACEHOLDER = 'Search your media'
export const LOAD_MORE_TEXT = 'Load more'
export const MANAGE_MEDIA_BUTTON_TEXT = 'Insert media'
export const MANAGE_COURSES_PAGE_HEADING = 'Your courses'
export const USERS_MANAGER_PAGE_HEADING = 'Users'
export const NEW_COURSE_PAGE_HEADING = 'New course'
export const MEDIA_MANAGER_DIALOG_TITLE = 'Add media'
export const BUTTON_NEW_COURSE = 'New course'
export const DIALOG_TITLE_FEATURED_IMAGE = 'Select featured image'
export const BUTTON_SET_FEATURED_IMAGE = 'Select'
export const BUTTON_IMAGE_CHANGE = 'Change'
export const FORM_FIELD_FEATURED_IMAGE = 'Featured image'
export const BTN_DELETE_COURSE = 'Delete course'
export const BTN_ADD_VIDEO = 'Add'
export const ADD_VIDEO_DIALOG_TITLE = 'Embed an online video'
export const CAPTION_VERIFIED = 'Verified'
export const CAPTION_UNVERIFIED = 'Not verified'
export const LABEL_NEW_PASSWORD = 'New password'
export const BUTTON_SAVE = 'Save'
export const SWITCH_IS_ADMIN = 'Admin'
export const SWITCH_IS_CREATOR = 'Creator'
export const SWITCH_ACCOUNT_ACTIVE = 'Account active'
export const LABEL_CONF_PASSWORD = 'Confirm password'
export const HEADER_ABOUT_SECTION = 'About'
export const HEADER_BLOG_POSTS_SECTION = 'Posts'
export const SITE_SETTINGS_TITLE = 'Title'
export const SITE_SETTINGS_SUBTITLE = 'Subtitle'
export const SITE_SETTINGS_CURRENCY_UNIT = 'Currency Unit'
export const SITE_SETTINGS_LOGO = 'Logo'
export const SITE_SETTINGS_COPYRIGHT_TEXT = 'Copyright Text'
export const SITE_SETTINGS_ABOUT_TEXT = 'About'
export const SITE_SETTINGS_PAGE_HEADING = 'Site Settings'
export const FREE_COST = 'FREE'
export const SIDEBAR_TEXT_COURSE_INTRODUCTION = 'Introduction'
export const REACT_COMPONENT_CRASHED = 'We\'ve encountered a problem in showing the content'
export const BUTTON_START_NOW = 'Start now'
export const BUTTON_TEXT_BUY_NOW = 'Buy now for'