import { Theme, ThemeStyle } from "@courselit/page-models";

const themeStyles: ThemeStyle = {
    colors: {
        light: {
            background: "#fcfcfc",
            foreground: "#000000",
            card: "#ffffff",
            cardForeground: "#000000",
            popover: "#fcfcfc",
            popoverForeground: "#000000",
            primary: "#000000",
            primaryForeground: "#ffffff",
            secondary: "#ebebeb",
            secondaryForeground: "#000000",
            muted: "#f5f5f5",
            mutedForeground: "#525252",
            accent: "#ebebeb",
            accentForeground: "#000000",
            destructive: "#e54b4f",
            border: "#e4e4e4",
            input: "#ebebeb",
            ring: "#000000",
            chart1: "#ffae04",
            chart2: "#2d62ef",
            chart3: "#a4a4a4",
            chart4: "#e4e4e4",
            chart5: "#747474",
            sidebar: "#fcfcfc",
            sidebarForeground: "#000000",
            sidebarPrimary: "#000000",
            sidebarPrimaryForeground: "#ffffff",
            sidebarAccent: "#ebebeb",
            sidebarAccentForeground: "#000000",
            sidebarBorder: "#ebebeb",
            sidebarRing: "#000000",
            shadow2xs: "0px 1px 2px 0px hsl(0 0% 0% / 0.09)",
            shadowXs: "0px 1px 2px 0px hsl(0 0% 0% / 0.09)",
            shadowSm:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 1px 2px -1px hsl(0 0% 0% / 0.18)",
            shadowMd:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 2px 4px -1px hsl(0 0% 0% / 0.18)",
            shadowLg:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 4px 6px -1px hsl(0 0% 0% / 0.18)",
            shadowXl:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 8px 10px -1px hsl(0 0% 0% / 0.18)",
            shadow2xl: "0px 1px 2px 0px hsl(0 0% 0% / 0.45)",
        },
        dark: {
            background: "#000000",
            foreground: "#ffffff",
            card: "#090909",
            cardForeground: "#ffffff",
            popover: "#121212",
            popoverForeground: "#ffffff",
            primary: "#ffffff",
            primaryForeground: "#000000",
            secondary: "#222222",
            secondaryForeground: "#ffffff",
            muted: "#1d1d1d",
            mutedForeground: "#a4a4a4",
            accent: "#333333",
            accentForeground: "#ffffff",
            destructive: "#ff5b5b",
            border: "#242424",
            input: "#333333",
            ring: "#a4a4a4",
            chart1: "#ffae04",
            chart2: "#2671f4",
            chart3: "#747474",
            chart4: "#525252",
            chart5: "#e4e4e4",
            sidebar: "#121212",
            sidebarForeground: "#ffffff",
            sidebarPrimary: "#ffffff",
            sidebarPrimaryForeground: "#000000",
            sidebarAccent: "#333333",
            sidebarAccentForeground: "#ffffff",
            sidebarBorder: "#333333",
            sidebarRing: "#a4a4a4",
            shadow2xs: "0px 1px 2px 0px hsl(0 0% 0% / 0.09)",
            shadowXs: "0px 1px 2px 0px hsl(0 0% 0% / 0.09)",
            shadowSm:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 1px 2px -1px hsl(0 0% 0% / 0.18)",
            shadowMd:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 2px 4px -1px hsl(0 0% 0% / 0.18)",
            shadowLg:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 4px 6px -1px hsl(0 0% 0% / 0.18)",
            shadowXl:
                "0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 8px 10px -1px hsl(0 0% 0% / 0.18)",
            shadow2xl: "0px 1px 2px 0px hsl(0 0% 0% / 0.45)",
        },
    },
    typography: {
        preheader: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-medium",
            lineHeight: "leading-normal",
            letterSpacing: "tracking-wide",
            textTransform: "uppercase",
        },
        header1: {
            fontFamily: "font-inter",
            fontSize: "text-4xl",
            fontWeight: "font-bold",
            lineHeight: "leading-tight",
            letterSpacing: "tracking-tight",
        },
        header2: {
            fontFamily: "font-inter",
            fontSize: "text-3xl",
            fontWeight: "font-bold",
            lineHeight: "leading-tight",
            letterSpacing: "tracking-tight",
        },
        header3: {
            fontFamily: "font-inter",
            fontSize: "text-2xl",
            fontWeight: "font-semibold",
            lineHeight: "leading-snug",
            letterSpacing: "tracking-normal",
        },
        header4: {
            fontFamily: "font-inter",
            fontSize: "text-xl",
            fontWeight: "font-semibold",
            lineHeight: "leading-snug",
            letterSpacing: "tracking-normal",
        },
        subheader1: {
            fontFamily: "font-inter",
            fontSize: "text-lg",
            fontWeight: "font-medium",
            lineHeight: "leading-relaxed",
            letterSpacing: "tracking-normal",
        },
        subheader2: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-medium",
            lineHeight: "leading-relaxed",
            letterSpacing: "tracking-normal",
        },
        text1: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
            letterSpacing: "tracking-normal",
        },
        text2: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
            letterSpacing: "tracking-normal",
        },
        caption: {
            fontFamily: "font-inter",
            fontSize: "text-xs",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
            letterSpacing: "tracking-normal",
        },
        link: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
            letterSpacing: "tracking-normal",
            textDecoration: "no-underline",
        },
        button: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-medium",
            lineHeight: "leading-normal",
            letterSpacing: "tracking-normal",
        },
        input: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-normal",
            lineHeight: "leading-normal",
            letterSpacing: "tracking-normal",
        },
    },
    interactives: {
        button: {
            padding: {
                x: "px-4",
                y: "py-2",
            },
            border: {
                width: "border-0",
                radius: "rounded-md",
                // style: "border-solid",
            },
            shadow: "shadow-sm",
            disabled: {
                opacity: "opacity-50",
                cursor: "cursor-not-allowed",
            },
            custom: "",
        },
        link: {
            custom: "",
            disabled: {
                color: "gray-400",
                cursor: "cursor-not-allowed",
            },
        },
        card: {
            padding: {
                x: "px-4",
                y: "py-4",
            },
            border: {
                width: "border",
                radius: "rounded-lg",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-all duration-300 hover:shadow-lg hover:-translate-y-1",
        },
        input: {
            borderRadius: "rounded-md",
            padding: {
                x: "px-3",
                y: "py-2",
            },
            border: {
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "",
            disabled: {
                opacity: "opacity-50",
                cursor: "cursor-not-allowed",
            },
        },
    },
    structure: {
        page: {
            width: "max-w-6xl",
        },
        section: {
            padding: {
                x: "px-4",
                y: "py-16",
            },
        },
    },
};

export const classic: Theme = {
    id: "classic",
    name: "Classic",
    theme: themeStyles,
};
