import { Theme, ThemeStyle } from "@courselit/page-models";

const themeStyles: ThemeStyle = {
    colors: {
        light: {
            background: "#FFFFFF",
            foreground: "#1a1a1a",
            card: "#FFFFFF",
            cardForeground: "#1a1a1a",
            popover: "#FFFFFF",
            popoverForeground: "#1a1a1a",
            primary: "#1E3A8A",
            primaryForeground: "#FFFFFF",
            secondary: "#D97706",
            secondaryForeground: "#FFFFFF",
            muted: "rgba(26, 26, 26, 0.7)",
            mutedForeground: "rgba(26, 26, 26, 0.7)",
            accent: "#3B82F6",
            accentForeground: "#FFFFFF",
            border: "#E5E7EB",
            destructive: "#EF4444",
            input: "#FFFFFF",
            ring: "#1E3A8A",
            chart1: "#1E3A8A",
            chart2: "#D97706",
            chart3: "#3B82F6",
            chart4: "#EF4444",
            chart5: "#9ca3af",
            sidebar: "#FFFFFF",
            sidebarForeground: "#1a1a1a",
            sidebarPrimary: "#1E3A8A",
            sidebarPrimaryForeground: "#FFFFFF",
            sidebarAccent: "#3B82F6",
            sidebarAccentForeground: "#FFFFFF",
            sidebarBorder: "#E5E7EB",
            sidebarRing: "#1E3A8A",
            shadow2xs: "0 1px 2px 0px hsl(220 40% 2% / 0.5)",
            shadowXs: "0 1px 2px 0px hsl(220 40% 2% / 0.5)",
            shadowSm: "0 2px 4px 0px hsl(220 40% 2% / 0.5)",
            shadowMd: "0 4px 12px 0px hsl(220 40% 2% / 0.5)",
            shadowLg: "0 8px 24px 0px hsl(220 40% 2% / 0.5)",
            shadowXl: "0 12px 32px 0px hsl(220 40% 2% / 0.5)",
            shadow2xl: "0 16px 48px 0px hsl(220 40% 2% / 0.5)",
        },
        dark: {
            background: "#111827",
            foreground: "#FFFFFF",
            card: "#1F2937",
            cardForeground: "#FFFFFF",
            popover: "#1F2937",
            popoverForeground: "#FFFFFF",
            primary: "#1E3A8A",
            primaryForeground: "#FFFFFF",
            secondary: "#D97706",
            secondaryForeground: "#FFFFFF",
            muted: "rgba(255, 255, 255, 0.7)",
            mutedForeground: "rgba(255, 255, 255, 0.7)",
            accent: "#3B82F6",
            accentForeground: "#FFFFFF",
            border: "#374151",
            destructive: "#EF4444",
            input: "#1F2937",
            ring: "#1E3A8A",
            chart1: "#1E3A8A",
            chart2: "#D97706",
            chart3: "#3B82F6",
            chart4: "#EF4444",
            chart5: "#9ca3af",
            sidebar: "#1F2937",
            sidebarForeground: "#FFFFFF",
            sidebarPrimary: "#1E3A8A",
            sidebarPrimaryForeground: "#FFFFFF",
            sidebarAccent: "#3B82F6",
            sidebarAccentForeground: "#FFFFFF",
            sidebarBorder: "#374151",
            sidebarRing: "#1E3A8A",
            shadow2xs: "0 1px 2px 0px hsl(220 40% 2% / 0.5)",
            shadowXs: "0 1px 2px 0px hsl(220 40% 2% / 0.5)",
            shadowSm: "0 2px 4px 0px hsl(220 40% 2% / 0.5)",
            shadowMd: "0 4px 12px 0px hsl(220 40% 2% / 0.5)",
            shadowLg: "0 8px 24px 0px hsl(220 40% 2% / 0.5)",
            shadowXl: "0 12px 32px 0px hsl(220 40% 2% / 0.5)",
            shadow2xl: "0 16px 48px 0px hsl(220 40% 2% / 0.5)",
        },
    },
    typography: {
        preheader: {
            fontFamily: "font-work-sans",
            fontSize: "text-sm",
            fontWeight: "font-medium",
            lineHeight: "leading-relaxed",
            letterSpacing: "tracking-wide",
        },
        header1: {
            fontFamily: "font-playfair-display",
            fontSize: "text-6xl",
            fontWeight: "font-semibold",
            lineHeight: "leading-tight",
            letterSpacing: "tracking-tighter",
        },
        header2: {
            fontFamily: "font-source-serif-4",
            fontSize: "text-4xl",
            fontWeight: "font-medium",
            lineHeight: "leading-tight",
            letterSpacing: "tracking-tighter",
        },
        header3: {
            fontFamily: "font-source-serif-4",
            fontSize: "text-3xl",
            fontWeight: "font-medium",
            lineHeight: "leading-snug",
            letterSpacing: "tracking-tighter",
        },
        header4: {
            fontFamily: "font-source-serif-4",
            fontSize: "text-2xl",
            fontWeight: "font-medium",
            lineHeight: "leading-snug",
            letterSpacing: "tracking-tighter",
        },
        subheader1: {
            fontFamily: "font-inter",
            fontSize: "text-lg",
            fontWeight: "font-medium",
            lineHeight: "leading-relaxed",
        },
        subheader2: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
        },
        text1: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
        },
        text2: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-light",
            lineHeight: "leading-relaxed",
        },
        link: {
            fontFamily: "font-work-sans",
            fontSize: "text-base",
            fontWeight: "font-medium",
        },
        button: {
            fontFamily: "font-work-sans",
            fontSize: "text-sm",
            fontWeight: "font-medium",
            textTransform: "uppercase",
            letterSpacing: "tracking-wide",
        },
        input: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
        },
        caption: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-normal",
            lineHeight: "leading-normal",
        },
    },
    interactives: {
        button: {
            padding: { x: "px-6", y: "py-3" },
            border: {
                width: "border-0",
                radius: "rounded-md",
                // style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-colors duration-200 ease-in-out hover:bg-[#1E3A8A] hover:text-white",
            disabled: {
                background: "#F3F4F6",
                opacity: "opacity-50",
                cursor: "cursor-not-allowed",
            },
        },
        link: {
            padding: { x: "px-1", y: "py-0" },
            custom: "transition-colors duration-150 ease-in-out hover:text-[#1E3A8A]",
        },
        card: {
            padding: { x: "px-6", y: "py-6" },
            border: {
                width: "border",
                radius: "rounded-lg",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-shadow duration-200 ease-in hover:shadow-lg",
        },
        input: {
            padding: { x: "px-4", y: "py-2" },
            border: {
                width: "border",
                radius: "rounded-md",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-colors duration-150 ease-in-out hover:border-[#1E3A8A]",
            disabled: {
                background: "#F3F4F6",
                opacity: "opacity-50",
                cursor: "cursor-not-allowed",
            },
        },
    },
    structure: {
        page: { width: "max-w-6xl" },
        section: {
            padding: { x: "px-4", y: "py-24" },
        },
    },
};

export const editorial: Theme = {
    id: "editorial",
    name: "Editorial",
    theme: themeStyles,
};
