import { Theme, ThemeStyle } from "@courselit/page-models";

const themeStyles: ThemeStyle = {
    colors: {
        light: {
            background: "#FFFFFF",
            foreground: "#282C34",
            card: "#FFFFFF",
            cardForeground: "#282C34",
            popover: "#FFFFFF",
            popoverForeground: "#282C34",
            primary: "#61AFEF",
            primaryForeground: "#FFFFFF",
            secondary: "#6366F1",
            secondaryForeground: "#FFFFFF",
            muted: "#9ca3af",
            mutedForeground: "#9ca3af",
            accent: "#56B6C2",
            accentForeground: "#FFFFFF",
            border: "#3E4451",
            destructive: "#E06C75",
            input: "#3E4451",
            ring: "#6366F1",
            chart1: "#61AFEF",
            chart2: "#6366F1",
            chart3: "#56B6C2",
            chart4: "#ABB2BF",
            chart5: "#3E4451",
            sidebar: "#282C34",
            sidebarForeground: "#FFFFFF",
            sidebarPrimary: "#61AFEF",
            sidebarPrimaryForeground: "#282C34",
            sidebarAccent: "#56B6C2",
            sidebarAccentForeground: "#FFFFFF",
            sidebarBorder: "#3E4451",
            sidebarRing: "#6366F1",
            shadow2xs: "0 1px 1px 0px rgba(62, 68, 81, 0.1)",
            shadowXs: "0 1px 2px 0px rgba(62, 68, 81, 0.15)",
            shadowSm: "0 2px 4px 0px rgba(62, 68, 81, 0.2)",
            shadowMd: "0 4px 8px 0px rgba(62, 68, 81, 0.25)",
            shadowLg: "0 8px 16px 0px rgba(62, 68, 81, 0.3)",
            shadowXl: "0 12px 24px 0px rgba(62, 68, 81, 0.35)",
            shadow2xl: "0 16px 32px 0px rgba(62, 68, 81, 0.4)",
        },
        dark: {
            background: "#282C34",
            foreground: "#ABB2BF",
            card: "#282C34",
            cardForeground: "#ABB2BF",
            popover: "#282C34",
            popoverForeground: "#ABB2BF",
            primary: "#61AFEF",
            primaryForeground: "#FFFFFF",
            secondary: "#6366F1",
            secondaryForeground: "#FFFFFF",
            muted: "#9ca3af",
            mutedForeground: "#9ca3af",
            accent: "#56B6C2",
            accentForeground: "#FFFFFF",
            border: "#3E4451",
            destructive: "#E06C75",
            input: "#3E4451",
            ring: "#6366F1",
            chart1: "#61AFEF",
            chart2: "#6366F1",
            chart3: "#56B6C2",
            chart4: "#ABB2BF",
            chart5: "#3E4451",
            sidebar: "#282C34",
            sidebarForeground: "#ABB2BF",
            sidebarPrimary: "#61AFEF",
            sidebarPrimaryForeground: "#282C34",
            sidebarAccent: "#56B6C2",
            sidebarAccentForeground: "#FFFFFF",
            sidebarBorder: "#3E4451",
            sidebarRing: "#6366F1",
            shadow2xs: "0 1px 1px 0px rgba(62, 68, 81, 0.1)",
            shadowXs: "0 1px 2px 0px rgba(62, 68, 81, 0.15)",
            shadowSm: "0 2px 4px 0px rgba(62, 68, 81, 0.2)",
            shadowMd: "0 4px 8px 0px rgba(62, 68, 81, 0.25)",
            shadowLg: "0 8px 16px 0px rgba(62, 68, 81, 0.3)",
            shadowXl: "0 12px 24px 0px rgba(62, 68, 81, 0.35)",
            shadow2xl: "0 16px 32px 0px rgba(62, 68, 81, 0.4)",
        },
    },
    typography: {
        preheader: {
            fontFamily: "font-roboto",
            fontSize: "text-xs",
            fontWeight: "font-normal",
            lineHeight: "leading-normal",
        },
        header1: {
            fontFamily: "font-roboto",
            fontSize: "text-5xl",
            fontWeight: "font-bold",
            lineHeight: "leading-tight",
        },
        header2: {
            fontFamily: "font-roboto",
            fontSize: "text-4xl",
            fontWeight: "font-semibold",
            lineHeight: "leading-tight",
        },
        header3: {
            fontFamily: "font-roboto",
            fontSize: "text-3xl",
            fontWeight: "font-medium",
            lineHeight: "leading-snug",
        },
        header4: {
            fontFamily: "font-roboto",
            fontSize: "text-2xl",
            fontWeight: "font-medium",
            lineHeight: "leading-snug",
        },
        subheader1: {
            fontFamily: "font-roboto",
            fontSize: "text-lg",
            fontWeight: "font-medium",
            lineHeight: "leading-relaxed",
        },
        subheader2: {
            fontFamily: "font-roboto",
            fontSize: "text-base",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
        },
        text1: {
            fontFamily: "font-roboto",
            fontSize: "text-base",
            fontWeight: "font-normal",
            lineHeight: "leading-relaxed",
        },
        text2: {
            fontFamily: "font-roboto",
            fontSize: "text-sm",
            fontWeight: "font-light",
            lineHeight: "leading-relaxed",
        },
        link: {
            fontFamily: "font-roboto",
            fontSize: "text-base",
            fontWeight: "font-medium",
            // textDecoration: "underline",
        },
        button: {
            fontFamily: "font-roboto",
            fontSize: "text-sm",
            fontWeight: "font-bold",
            textTransform: "uppercase",
        },
        input: {
            fontFamily: "font-roboto",
            fontSize: "text-base",
            fontWeight: "font-normal",
        },
        caption: {
            fontFamily: "font-roboto",
            fontSize: "text-xs",
            fontWeight: "font-normal",
            lineHeight: "leading-normal",
        },
    },
    interactives: {
        button: {
            padding: { x: "px-4", y: "py-2" },
            border: {
                width: "border",
                radius: "rounded-none",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-all duration-200 ease-in-out hover:bg-blue-400 hover:text-black hover:shadow-md hover:scale-105",
            disabled: {
                background: "bg-slate-700",
                opacity: "opacity-50",
                cursor: "cursor-not-allowed",
            },
        },
        link: {
            padding: { x: "px-1", y: "py-0" },
            custom: "hover:underline",
        },
        card: {
            padding: { x: "px-6", y: "py-6" },
            border: {
                width: "border",
                radius: "rounded-none",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-shadow duration-200 ease-in hover:shadow-md",
        },
        input: {
            padding: { x: "px-4", y: "py-2" },
            border: {
                width: "border",
                radius: "rounded-none",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-colors duration-150 ease-in-out hover:border-blue-400",
            disabled: {
                background: "bg-slate-700",
                opacity: "opacity-50",
                cursor: "cursor-not-allowed",
            },
        },
    },
    structure: {
        page: { width: "max-w-6xl" },
        section: {
            padding: { x: "px-4", y: "py-10" },
        },
    },
};

export const midnight: Theme = {
    id: "midnight",
    name: "Midnight",
    theme: themeStyles,
};
