import { Theme, ThemeStyle } from "@courselit/page-models";

const themeStyles: ThemeStyle = {
    colors: {
        light: {
            background: "#6FFFD7",
            foreground: "#000000",
            card: "#6FFFD7",
            cardForeground: "#000000",
            popover: "#6FFFD7",
            popoverForeground: "#000000",
            primary: "#FFF700",
            primaryForeground: "#000000",
            secondary: "#7DF9FF",
            secondaryForeground: "#000000",
            muted: "#9ca3af",
            mutedForeground: "#9ca3af",
            accent: "#2FF2F2",
            accentForeground: "#000000",
            border: "#000000",
            destructive: "#FF4911",
            input: "#000000",
            ring: "#000000",
            chart1: "#FFF700",
            chart2: "#7DF9FF",
            chart3: "#2FF2F2",
            chart4: "#FF4911",
            chart5: "#6FFFD7",
            sidebar: "#6FFFD7",
            sidebarForeground: "#000000",
            sidebarPrimary: "#FFF700",
            sidebarPrimaryForeground: "#000000",
            sidebarAccent: "#2FF2F2",
            sidebarAccentForeground: "#000000",
            sidebarBorder: "#000000",
            sidebarRing: "#000000",
            shadow2xs: "1px 1px 0px 0px #000000",
            shadowXs: "2px 2px 0px 0px #000000",
            shadowSm: "3px 3px 0px 0px #000000",
            shadowMd: "5px 5px 0px 0px #000000",
            shadowLg: "6px 6px 0px 0px #000000",
            shadowXl: "7px 7px 0px 0px #000000",
            shadow2xl: "8px 8px 0px 0px #000000",
        },
        dark: {
            background: "#000000",
            foreground: "#6FFFD7",
            card: "#000000",
            cardForeground: "#6FFFD7",
            popover: "#000000",
            popoverForeground: "#6FFFD7",
            primary: "#FFF700",
            primaryForeground: "#000000",
            secondary: "#7DF9FF",
            secondaryForeground: "#000000",
            muted: "#9ca3af",
            mutedForeground: "#9ca3af",
            accent: "#2FF2F2",
            accentForeground: "#000000",
            border: "#6FFFD7",
            destructive: "#FF4911",
            input: "#6FFFD7",
            ring: "#6FFFD7",
            chart1: "#FFF700",
            chart2: "#7DF9FF",
            chart3: "#2FF2F2",
            chart4: "#FF4911",
            chart5: "#6FFFD7",
            sidebar: "#000000",
            sidebarForeground: "#6FFFD7",
            sidebarPrimary: "#FFF700",
            sidebarPrimaryForeground: "#000000",
            sidebarAccent: "#2FF2F2",
            sidebarAccentForeground: "#000000",
            sidebarBorder: "#6FFFD7",
            sidebarRing: "#6FFFD7",
            shadow2xs: "1px 1px 0 0 #6FFFD7",
            shadowXs: "2px 2px 0 0 #6FFFD7",
            shadowSm: "3px 3px 0 0 #6FFFD7",
            shadowMd: "5px 5px 0 0 #6FFFD7",
            shadowLg: "6px 6px 0 0 #6FFFD7",
            shadowXl: "7px 7px 0 0 #6FFFD7",
            shadow2xl: "8px 8px 0 0 #6FFFD7",
        },
    },
    typography: {
        preheader: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-normal",
        },
        header1: {
            fontFamily: "font-inter",
            fontSize: "text-3xl",
            fontWeight: "font-bold",
            textTransform: "normal-case",
        },
        header2: {
            fontFamily: "font-inter",
            fontSize: "text-2xl",
            fontWeight: "font-bold",
            textTransform: "normal-case",
        },
        header3: {
            fontFamily: "font-inter",
            fontSize: "text-xl",
            fontWeight: "font-bold",
            textTransform: "normal-case",
        },
        header4: {
            fontFamily: "font-inter",
            fontSize: "text-lg",
            fontWeight: "font-bold",
            textTransform: "normal-case",
        },
        subheader1: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
        },
        subheader2: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-normal",
        },
        text1: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
        },
        text2: {
            fontFamily: "font-inter",
            fontSize: "text-sm",
            fontWeight: "font-normal",
        },
        link: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-semibold",
        },
        button: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-bold",
            textTransform: "normal-case",
        },
        input: {
            fontFamily: "font-inter",
            fontSize: "text-base",
            fontWeight: "font-normal",
        },
        caption: {
            fontFamily: "font-inter",
            fontSize: "text-xs",
            fontWeight: "font-normal",
        },
    },
    interactives: {
        button: {
            padding: { x: "px-4", y: "py-2" },
            border: {
                width: "border-2",
                radius: "rounded-none",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-all duration-200 ease-in-out hover:shadow-none hover:translate-x-1 hover:translate-y-1",
            disabled: {
                background: "#F3F4F6",
                opacity: "opacity-50",
                cursor: "cursor-not-allowed",
            },
        },
        link: {
            padding: { x: "px-1", y: "py-0" },
            custom: "hover:underline",
        },
        card: {
            padding: { x: "px-6", y: "py-6" },
            border: {
                width: "border-2",
                radius: "rounded-none",
                style: "border-solid",
            },
            shadow: "shadow-sm",
            custom: "transition-all duration-200 ease-in-out hover:translate-y-1",
        },
        input: {
            padding: { x: "px-4", y: "py-2" },
            border: {
                width: "border-2",
                style: "border-solid",
                radius: "rounded-none",
            },
            shadow: "shadow-sm",
            custom: "transition-all duration-150 ease-in-out hover:shadow-none hover:translate-x-1 hover:translate-y-1",
            disabled: {
                background: "#F3F4F6",
                cursor: "cursor-not-allowed",
                opacity: "opacity-50",
            },
        },
    },
    structure: {
        page: { width: "max-w-6xl" },
        section: {
            padding: { x: "px-4", y: "py-10" },
        },
    },
};

export const neobrutalism: Theme = {
    id: "neobrutalism",
    name: "Neo-Brutalism",
    theme: themeStyles,
};
