/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by @codelitdev/billing schema version 2.
 */
import { sql } from "drizzle-orm";
import {
    boolean,
    check,
    index,
    integer,
    pgTable,
    text,
    timestamp,
    uniqueIndex,
    uuid,
} from "drizzle-orm/pg-core";
// The generated artifact is also loaded directly by drizzle-kit, which resolves
// extensionless application TypeScript imports. Keep those imports portable for
// the consuming application's module resolver.
// @ts-ignore drizzle-kit resolves the extensionless TypeScript import.
import { schools } from "./schools";
// @ts-ignore drizzle-kit resolves the extensionless TypeScript import.
import { user } from "./auth.generated";

const timestamps = {
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

export const billingPriceEntries = pgTable(
    "billing_price_entries",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        offerKey: text("offer_key").notNull(),
        plan: text("plan").notNull(),
        billingInterval: text("billing_interval").notNull(),
        currency: text("currency").notNull(),
        amountMinor: integer("amount_minor").notNull(),
        providerTrialDays: integer("provider_trial_days").notNull().default(0),
        provider: text("provider").notNull(),
        providerProductId: text("provider_product_id").notNull(),
        verifiedAt: timestamp("verified_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => ({
        providerProductUnique: uniqueIndex("billing_price_entries_provider_product_uidx").on(
            table.provider,
            table.providerProductId,
        ),
        offerKeyIdx: index("billing_price_entries_offer_key_idx").on(table.offerKey),
        amountCheck: check("billing_price_entries_amount_check", sql`${table.amountMinor} > 0`),
        trialDaysCheck: check("billing_price_entries_trial_days_check", sql`${table.providerTrialDays} >= 0`),
        currencyCheck: check("billing_price_entries_currency_check", sql`${table.currency} ~ '^[A-Z]{3}$'`),
        planCheck: check("billing_price_entries_plan_check", sql`${table.plan} IN ('pro', 'business')`),
        intervalCheck: check(
            "billing_price_entries_interval_check",
            sql`${table.billingInterval} IN ('month', 'year')`,
        ),
    }),
);

export const billingCatalogRevisions = pgTable(
    "billing_catalog_revisions",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        revision: integer("revision").notNull().unique(),
        checkoutProvider: text("checkout_provider").notNull(),
        status: text("status").notNull().default("pending_verification"),
        verifiedAt: timestamp("verified_at", { withTimezone: true }),
        activatedAt: timestamp("activated_at", { withTimezone: true }),
        retiredAt: timestamp("retired_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => ({
        statusCheck: check(
            "billing_catalog_revisions_status_check",
            sql`${table.status} IN ('pending_verification', 'active', 'retired', 'invalid', 'abandoned')`,
        ),
        revisionCheck: check("billing_catalog_revisions_revision_check", sql`${table.revision} > 0`),
        activeProviderUnique: uniqueIndex("billing_catalog_revisions_active_provider_uidx")
            .on(table.checkoutProvider)
            .where(sql`${table.status} = 'active'`),
    }),
);

export const billingCatalogRevisionItems = pgTable(
    "billing_catalog_revision_items",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        catalogRevisionId: uuid("catalog_revision_id")
            .notNull()
            .references(() => billingCatalogRevisions.id, { onDelete: "cascade" }),
        offerKey: text("offer_key").notNull(),
        billingPriceEntryId: uuid("billing_price_entry_id")
            .notNull()
            .references(() => billingPriceEntries.id, { onDelete: "restrict" }),
    },
    (table) => ({
        revisionKeyUnique: uniqueIndex("billing_catalog_revision_items_revision_key_uidx").on(
            table.catalogRevisionId,
            table.offerKey,
        ),
        revisionPriceUnique: uniqueIndex("billing_catalog_revision_items_revision_price_uidx").on(
            table.catalogRevisionId,
            table.billingPriceEntryId,
        ),
    }),
);

export const billingProviderCustomers = pgTable(
    "billing_provider_customers",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        provider: text("provider").notNull(),
        payerId: text("payer_id")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        payerEmail: text("payer_email").notNull().default(""),
        providerCustomerId: text("provider_customer_id"),
        idempotencyKey: text("idempotency_key").notNull(),
        status: text("status").notNull().default("creating"),
        lastError: text("last_error"),
        ...timestamps,
    },
    (table) => ({
        providerPayerUnique: uniqueIndex("billing_provider_customers_provider_payer_uidx").on(
            table.provider,
            table.payerId,
        ),
        providerCustomerUnique: uniqueIndex("billing_provider_customers_provider_customer_uidx")
            .on(table.provider, table.providerCustomerId)
            .where(sql`${table.providerCustomerId} IS NOT NULL`),
        idempotencyUnique: uniqueIndex("billing_provider_customers_idempotency_uidx").on(
            table.idempotencyKey,
        ),
        statusCheck: check(
            "billing_provider_customers_status_check",
            sql`${table.status} IN ('creating', 'active', 'conflicted')`,
        ),
    }),
);

export const billingCheckoutAttempts = pgTable(
    "billing_checkout_attempts",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        attemptId: text("attempt_id").notNull().unique(),
        billableEntityId: uuid("billable_entity_id")
            .notNull()
            .references(() => schools.id, { onDelete: "restrict" }),
        payerId: text("payer_id")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        payerEmail: text("payer_email").notNull().default(""),
        returnUrl: text("return_url").notNull().default(""),
        provider: text("provider").notNull(),
        catalogRevision: integer("catalog_revision").notNull(),
        offerKey: text("offer_key").notNull(),
        requestedPlan: text("requested_plan").notNull(),
        requestedInterval: text("requested_interval").notNull(),
        billingPriceEntryId: uuid("billing_price_entry_id")
            .notNull()
            .references(() => billingPriceEntries.id, { onDelete: "restrict" }),
        quotedAmountMinor: integer("quoted_amount_minor").notNull(),
        quotedCurrency: text("quoted_currency").notNull(),
        billingCustomerId: uuid("billing_customer_id").references(
            () => billingProviderCustomers.id,
            { onDelete: "restrict" },
        ),
        providerCheckoutSessionId: text("provider_checkout_session_id"),
        checkoutUrlEncrypted: text("checkout_url_encrypted"),
        idempotencyKey: text("idempotency_key").notNull(),
        status: text("status").notNull().default("creating"),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        lastError: text("last_error"),
        completedAt: timestamp("completed_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => ({
        providerSessionUnique: uniqueIndex("billing_checkout_attempts_provider_session_uidx")
            .on(table.provider, table.providerCheckoutSessionId)
            .where(sql`${table.providerCheckoutSessionId} IS NOT NULL`),
        idempotencyUnique: uniqueIndex("billing_checkout_attempts_idempotency_uidx").on(
            table.idempotencyKey,
        ),
        entityNonterminalUnique: uniqueIndex("billing_checkout_attempts_entity_nonterminal_uidx")
            .on(table.billableEntityId)
            .where(sql`${table.status} IN ('creating', 'open')`),
        statusCheck: check(
            "billing_checkout_attempts_status_check",
            sql`${table.status} IN ('creating', 'open', 'completed', 'expired', 'abandoned', 'conflicted')`,
        ),
        amountCheck: check(
            "billing_checkout_attempts_amount_check",
            sql`${table.quotedAmountMinor} > 0`,
        ),
        planCheck: check(
            "billing_checkout_attempts_plan_check",
            sql`${table.requestedPlan} IN ('pro', 'business')`,
        ),
        intervalCheck: check(
            "billing_checkout_attempts_interval_check",
            sql`${table.requestedInterval} IN ('month', 'year')`,
        ),
    }),
);

export const billingSubscriptions = pgTable(
    "billing_subscriptions",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        billableEntityId: uuid("billable_entity_id")
            .notNull()
            .references(() => schools.id, { onDelete: "restrict" }),
        billingCustomerId: uuid("billing_customer_id")
            .notNull()
            .references(() => billingProviderCustomers.id, { onDelete: "restrict" }),
        payerId: text("payer_id")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        originCheckoutAttemptId: uuid("origin_checkout_attempt_id").references(
            () => billingCheckoutAttempts.id,
            { onDelete: "restrict" },
        ),
        provider: text("provider").notNull(),
        providerSubscriptionId: text("provider_subscription_id").notNull(),
        providerProductId: text("provider_product_id").notNull(),
        billingPriceEntryId: uuid("billing_price_entry_id")
            .notNull()
            .references(() => billingPriceEntries.id, { onDelete: "restrict" }),
        catalogRevision: integer("catalog_revision").notNull(),
        offerKey: text("offer_key").notNull(),
        plan: text("plan").notNull(),
        billingInterval: text("billing_interval").notNull(),
        status: text("status").notNull().default("pending"),
        currentPeriodStartsAt: timestamp("current_period_starts_at", { withTimezone: true }),
        currentPeriodEndsAt: timestamp("current_period_ends_at", { withTimezone: true }),
        paidThroughAt: timestamp("paid_through_at", { withTimezone: true }),
        trialEndsAt: timestamp("trial_ends_at", { withTimezone: true }),
        cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),
        isEntitlementSource: boolean("is_entitlement_source").notNull().default(false),
        providerOccurredAt: timestamp("provider_occurred_at", { withTimezone: true }),
        providerVersion: text("provider_version"),
        lastObservedAt: timestamp("last_observed_at", { withTimezone: true }),
        lastReconciledAt: timestamp("last_reconciled_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => ({
        providerSubscriptionUnique: uniqueIndex("billing_subscriptions_provider_subscription_uidx").on(
            table.provider,
            table.providerSubscriptionId,
        ),
        entitySourceUnique: uniqueIndex("billing_subscriptions_entity_source_uidx")
            .on(table.billableEntityId)
            .where(sql`${table.isEntitlementSource} = true`),
        statusCheck: check(
            "billing_subscriptions_status_check",
            sql`${table.status} IN ('pending', 'trialing', 'active', 'past_due', 'cancelled', 'expired')`,
        ),
        planCheck: check("billing_subscriptions_plan_check", sql`${table.plan} IN ('pro', 'business')`),
        intervalCheck: check(
            "billing_subscriptions_interval_check",
            sql`${table.billingInterval} IN ('month', 'year')`,
        ),
    }),
);

export const billingPlanChangeAttempts = pgTable(
    "billing_plan_change_attempts",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        changeId: text("change_id").notNull().unique(),
        billableEntityId: uuid("billable_entity_id")
            .notNull()
            .references(() => schools.id, { onDelete: "restrict" }),
        subscriptionId: uuid("subscription_id")
            .notNull()
            .references(() => billingSubscriptions.id, { onDelete: "restrict" }),
        actorId: text("actor_id").notNull(),
        payerId: text("payer_id")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        provider: text("provider").notNull(),
        idempotencyKey: text("idempotency_key").notNull(),
        currentCatalogRevision: integer("current_catalog_revision").notNull(),
        currentBillingPriceEntryId: uuid("current_billing_price_entry_id")
            .notNull()
            .references(() => billingPriceEntries.id, { onDelete: "restrict" }),
        currentPlan: text("current_plan").notNull(),
        currentInterval: text("current_interval").notNull(),
        targetCatalogRevision: integer("target_catalog_revision").notNull(),
        targetBillingPriceEntryId: uuid("target_billing_price_entry_id")
            .notNull()
            .references(() => billingPriceEntries.id, { onDelete: "restrict" }),
        targetPlan: text("target_plan").notNull(),
        targetInterval: text("target_interval").notNull(),
        targetOfferKey: text("target_offer_key").notNull(),
        effectiveAt: text("effective_at").notNull(),
        prorationMode: text("proration_mode").notNull(),
        providerPaymentId: text("provider_payment_id"),
        paymentUrlEncrypted: text("payment_url_encrypted"),
        status: text("status").notNull().default("creating"),
        lastError: text("last_error"),
        completedAt: timestamp("completed_at", { withTimezone: true }),
        ...timestamps,
    },
    (table) => ({
        idempotencyUnique: uniqueIndex("billing_plan_change_attempts_idempotency_uidx").on(
            table.idempotencyKey,
        ),
        entityNonterminalUnique: uniqueIndex("billing_plan_change_attempts_entity_nonterminal_uidx")
            .on(table.billableEntityId)
            .where(sql`${table.status} IN ('creating', 'pending')`),
        statusCheck: check(
            "billing_plan_change_attempts_status_check",
            sql`${table.status} IN ('creating', 'pending', 'succeeded', 'failed', 'conflicted')`,
        ),
        effectiveAtCheck: check(
            "billing_plan_change_attempts_effective_at_check",
            sql`${table.effectiveAt} IN ('immediately', 'next_billing_date')`,
        ),
        prorationModeCheck: check(
            "billing_plan_change_attempts_proration_mode_check",
            sql`${table.prorationMode} IN ('prorated_immediately', 'do_not_bill')`,
        ),
        currentPlanCheck: check(
            "billing_plan_change_attempts_current_plan_check",
            sql`${table.currentPlan} IN ('pro', 'business')`,
        ),
        targetPlanCheck: check(
            "billing_plan_change_attempts_target_plan_check",
            sql`${table.targetPlan} IN ('pro', 'business')`,
        ),
    }),
);

export const billingPlanStates = pgTable(
    "billing_plan_states",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        billableEntityId: uuid("billable_entity_id")
            .notNull()
            .unique()
            .references(() => schools.id, { onDelete: "restrict" }),
        activeSubscriptionId: uuid("active_subscription_id").references(
            () => billingSubscriptions.id,
            { onDelete: "restrict" },
        ),
        projectionVersion: integer("projection_version").notNull().default(0),
        ...timestamps,
    },
);

export const billingWebhookEvents = pgTable(
    "billing_webhook_events",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        provider: text("provider").notNull(),
        providerEventId: text("provider_event_id").notNull(),
        eventType: text("event_type").notNull(),
        occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
        subscriptionId: text("subscription_id"),
        checkoutAttemptId: text("checkout_attempt_id"),
        payloadEncrypted: text("payload_encrypted"),
        payloadKeyVersion: text("payload_key_version"),
        verifiedKeyVersion: text("verified_key_version"),
        status: text("status").notNull().default("pending"),
        processingAttempts: integer("processing_attempts").notNull().default(0),
        lastError: text("last_error"),
        availableAt: timestamp("available_at", { withTimezone: true }).notNull().defaultNow(),
        lockedAt: timestamp("locked_at", { withTimezone: true }),
        leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
        workerId: text("worker_id"),
        receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
        processedAt: timestamp("processed_at", { withTimezone: true }),
    },
    (table) => ({
        providerEventUnique: uniqueIndex("billing_webhook_events_provider_event_uidx").on(
            table.provider,
            table.providerEventId,
        ),
        queueIdx: index("billing_webhook_events_queue_idx").on(table.status, table.availableAt),
        statusCheck: check(
            "billing_webhook_events_status_check",
            sql`${table.status} IN ('pending', 'processing', 'processed', 'ignored', 'quarantined', 'failed')`,
        ),
    }),
);

export const billingReconciliationJobs = pgTable(
    "billing_reconciliation_jobs",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        provider: text("provider").notNull(),
        checkoutAttemptId: uuid("checkout_attempt_id").references(
            () => billingCheckoutAttempts.id,
            { onDelete: "restrict" },
        ),
        planChangeAttemptId: uuid("plan_change_attempt_id").references(
            () => billingPlanChangeAttempts.id,
            { onDelete: "restrict" },
        ),
        subscriptionId: uuid("subscription_id").references(
            () => billingSubscriptions.id,
            { onDelete: "restrict" },
        ),
        providerCustomerId: uuid("provider_customer_id").references(
            () => billingProviderCustomers.id,
            { onDelete: "restrict" },
        ),
        operation: text("operation").notNull().default("reconcile"),
        status: text("status").notNull().default("pending"),
        attemptCount: integer("attempt_count").notNull().default(0),
        availableAt: timestamp("available_at", { withTimezone: true }).notNull().defaultNow(),
        lockedAt: timestamp("locked_at", { withTimezone: true }),
        leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
        workerId: text("worker_id"),
        lastError: text("last_error"),
        ...timestamps,
    },
    (table) => ({
        exactlyOneSubject: check(
            "billing_reconciliation_jobs_exactly_one_subject",
            sql`((CASE WHEN ${table.checkoutAttemptId} IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN ${table.planChangeAttemptId} IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN ${table.subscriptionId} IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN ${table.providerCustomerId} IS NOT NULL THEN 1 ELSE 0 END)) = 1`,
        ),
        liveCheckoutUnique: uniqueIndex("billing_reconciliation_jobs_live_checkout_uidx")
            .on(table.checkoutAttemptId)
            .where(sql`${table.checkoutAttemptId} IS NOT NULL AND ${table.status} IN ('pending', 'processing', 'failed')`),
        livePlanChangeUnique: uniqueIndex("billing_reconciliation_jobs_live_plan_change_uidx")
            .on(table.planChangeAttemptId)
            .where(sql`${table.planChangeAttemptId} IS NOT NULL AND ${table.status} IN ('pending', 'processing', 'failed')`),
        liveSubscriptionUnique: uniqueIndex("billing_reconciliation_jobs_live_subscription_uidx")
            .on(table.subscriptionId)
            .where(sql`${table.subscriptionId} IS NOT NULL AND ${table.status} IN ('pending', 'processing', 'failed')`),
        liveCustomerUnique: uniqueIndex("billing_reconciliation_jobs_live_customer_uidx")
            .on(table.providerCustomerId)
            .where(sql`${table.providerCustomerId} IS NOT NULL AND ${table.status} IN ('pending', 'processing', 'failed')`),
        statusCheck: check(
            "billing_reconciliation_jobs_status_check",
            sql`${table.status} IN ('pending', 'processing', 'failed', 'completed', 'quarantined')`,
        ),
        operationCheck: check(
            "billing_reconciliation_jobs_operation_check",
            sql`${table.operation} = 'reconcile' OR (${table.operation} = 'cancellation' AND ${table.subscriptionId} IS NOT NULL)`,
        ),
    }),
);
