/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by Better Auth getSchema (better-auth/db) from the reference
 * Better Auth options (the learner email-OTP and SSO realm).
 * Importing this module performs no DDL.
 */
import { boolean, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const learnerUser = pgTable("learner_user", {
        id: text("id").primaryKey(),
        name: text("name").notNull(),
        email: text("email").notNull().unique(),
        emailVerified: boolean("email_verified").notNull(),
        image: text("image"),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const learnerSession = pgTable("learner_session", {
        id: text("id").primaryKey(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        token: text("token").notNull().unique(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),
        userId: text("user_id").notNull().references(() => learnerUser.id, { onDelete: "cascade" }),
});

export const learnerAccount = pgTable("learner_account", {
        id: text("id").primaryKey(),
        issuer: text("issuer").notNull(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),
        userId: text("user_id").notNull().references(() => learnerUser.id, { onDelete: "cascade" }),
        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
        scope: text("scope"),
        password: text("password"),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const learnerVerification = pgTable("learner_verification", {
        id: text("id").primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const learnerSsoProvider = pgTable("learner_sso_provider", {
        id: text("id").primaryKey(),
        issuer: text("issuer").notNull(),
        oidcConfig: text("oidc_config"),
        samlConfig: text("saml_config"),
        userId: text("user_id").references(() => learnerUser.id, { onDelete: "cascade" }),
        providerId: text("provider_id").notNull().unique(),
        organizationId: text("organization_id"),
        domainString: text("domain_string").notNull(),
});
