import {
    BulletListExtension,
    DocExtension,
    DropCursorExtension,
    HeadingExtension,
    ImageExtension,
    LinkExtension,
    OrderedListExtension,
    ParagraphExtension,
    PlaceholderExtension,
    TaskListExtension,
    TextExtension,
    BlockquoteExtension,
    HardBreakExtension,
    BoldExtension,
    ItalicExtension,
    GapCursorExtension,
    HorizontalRuleExtension,
    StrikeExtension,
    UnderlineExtension,
    CodeExtension,
    BidiExtension,
    CodeBlockExtension,
    TrailingNodeExtension,
    IframeExtension,
    ShortcutsExtension,
} from "remirror/extensions";
import { CodeMirrorExtension } from "@remirror/extension-codemirror6";
import { TableExtension } from "@remirror/extension-react-tables";
import { oneDark } from "@codemirror/theme-one-dark";
import { basicSetup } from "codemirror";
import { getUploadHandler } from "./file-upload-extention";

export const getExtensions = (placeholder, url) => () => [
    new DocExtension({}),
    new TextExtension(),
    new ParagraphExtension(),
    new HeadingExtension({}),
    new BulletListExtension({}),
    new LinkExtension({}),
    new OrderedListExtension(),
    new PlaceholderExtension({ placeholder }),
    new TableExtension(),
    new TaskListExtension(),
    new ImageExtension({
        enableResizing: true,
        uploadHandler: getUploadHandler(url),
    }),
    new DropCursorExtension({
        color: "hsl(var(--foreground))",
    }),
    new CodeMirrorExtension({
        extensions: [basicSetup, oneDark],
    }),
    new BlockquoteExtension(),
    new HardBreakExtension(),
    new BoldExtension(null),
    new ItalicExtension(),
    new HardBreakExtension(),
    new GapCursorExtension(),
    new HardBreakExtension(),
    new HorizontalRuleExtension(),
    new StrikeExtension(),
    new UnderlineExtension(),
    new BlockquoteExtension(),
    new CodeExtension(),
    new BidiExtension(null),
    new CodeBlockExtension(null),
    new DropCursorExtension(),
    new HeadingExtension(null),
    new TrailingNodeExtension(),
    new IframeExtension({ enableResizing: false }),
    new BulletListExtension({}),
    new OrderedListExtension(),
    new TaskListExtension(),
    new ShortcutsExtension(),
];
