name: Publish NPM packages

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CI Git User
        run: |
          git config --global user.name 'CodeLit'
          git config --global user.email 'hi@codelit.dev'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
        env:
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Checkout and pull branch
        run: |
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install Packages
        run: pnpm install

      - name: Create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish 
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Echo changeset output
        run: echo "${{ steps.changesets.outputs.hasChangesets }}"
