name: Testing
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10.22.0
    - uses: actions/setup-node@v4
      with:
        node-version: "24"
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - name: Build packages
      run: |
          pnpm --filter @courselit/icons build
          pnpm --filter @courselit/page-models build
          pnpm --filter @courselit/email-editor build
          pnpm --filter @courselit/common-models build
          pnpm --filter @courselit/utils build
          pnpm --filter @courselit/text-editor build
          pnpm --filter @courselit/components-library build
          pnpm --filter @courselit/page-primitives build
          pnpm --filter @courselit/page-blocks build
    - name: Running tests
      run: |
        pnpm test
      working-directory: ./
